void Sending_To_phpmyadmindatabase() {

//  substring = asciiString.substring(0, 7);

  if (client.connect(server, 8070)) {
    Serial.println("connected");
    // Make a HTTP request:
    Serial.print("GET /Battery_data_logger.php?id=");
    client.print("GET /Battery_data_logger.php?id=");  //YOUR URL
    Serial.println("DL_04");
    client.print("DL_04");
    Serial.print("&voltage=");
    client.print("&voltage=");  //YOUR URL
    Serial.println(Voltage * 0.1);
    client.print(Voltage * 0.1);
    client.print("&current=");  
    Serial.print("&current=");
    Serial.println(Current * 0.1);
    client.print(Current * 0.1);
    client.print("&soc=");  
    Serial.print("&soc=");
    Serial.println(SOC * 0.1);
    client.print(SOC * 0.1);
    client.print("&remainingAh=");  
    Serial.print("&remainingAh=");
    Serial.println(remainingAh);
    client.print(remainingAh);
    client.print("&cellvoltage1=");  
    Serial.print("&cellvoltage1=");
    Serial.println(CellVoltage1 * 0.001);
    client.print(CellVoltage1 * 0.001);
    client.print("&cellvoltage2=");  
    Serial.print("&cellvoltage2=");
    Serial.println(CellVoltage2 * 0.001);
    client.print(CellVoltage2 * 0.001);
    client.print("&cellvoltage3=");  
    Serial.print("&cellvoltage3=");
    Serial.println(CellVoltage3 * 0.001);
    client.print(CellVoltage3 * 0.001);
    client.print("&cellvoltage4=");  
    Serial.print("&cellvoltage4=");
    Serial.println(CellVoltage4 * 0.001);
    client.print(CellVoltage4 * 0.001);
    client.print("&cellvoltage5=");  
    Serial.print("&cellvoltage5=");
    Serial.println(CellVoltage5 * 0.001);
    client.print(CellVoltage5 * 0.001);
    client.print("&cellvoltage6=");  
    Serial.print("&cellvoltage6=");
    Serial.println(CellVoltage6 * 0.001);
    client.print(CellVoltage6 * 0.001);
    client.print("&cellvoltage7=");  
    Serial.print("&cellvoltage7=");
    Serial.println(CellVoltage7 * 0.001);
    client.print(CellVoltage7 * 0.001);
    client.print("&cellvoltage8=");  
    Serial.print("&cellvoltage8=");
    Serial.println(CellVoltage8 * 0.001);
    client.print(CellVoltage8 * 0.001);
    client.print("&cellvoltage9=");  
    Serial.print("&cellvoltage9=");
    Serial.println(CellVoltage9 * 0.001);
    client.print(CellVoltage9 * 0.001);
    client.print("&cellvoltage10=");  
    Serial.print("&cellvoltage10=");
    Serial.println(CellVoltage10 * 0.001);
    client.print(CellVoltage10 * 0.001);
    client.print("&cellvoltage11=");  
    Serial.print("&cellvoltage11=");
    Serial.println(CellVoltage11 * 0.001);
    client.print(CellVoltage11 * 0.001);
    client.print("&cellvoltage12=");  
    Serial.print("&cellvoltage12=");
    Serial.println(CellVoltage12 * 0.001);
    client.print(CellVoltage12 * 0.001);
    client.print("&cellvoltage13=");  
    Serial.print("&cellvoltage13=");
    Serial.println(CellVoltage13 * 0.001);
    client.print(CellVoltage13 * 0.001);
    client.print("&cellvoltage14=");  
    Serial.print("&cellvoltage14=");
    Serial.println(CellVoltage14 * 0.001);
    client.print(CellVoltage14 * 0.001);
    client.print("&cellvoltage15=");  
    Serial.print("&cellvoltage15=");
    Serial.println(CellVoltage15 * 0.001);
    client.print(CellVoltage15 * 0.001);
    client.print("&cellvoltage16=");  
    Serial.print("&cellvoltage16=");
    Serial.println(CellVoltage16 * 0.001);
    client.print(CellVoltage16 * 0.001);
    client.print("&cellvoltage17=");  
    Serial.print("&cellvoltage17=");
    Serial.println(CellVoltage17 * 0.001);
    client.print(CellVoltage17 * 0.001);
    client.print("&cellvoltage18=");  
    Serial.print("&cellvoltage18=");
    Serial.println(CellVoltage18 * 0.001);
    client.print(CellVoltage18 * 0.001);
    client.print("&cellvoltage19=");  
    Serial.print("&cellvoltage19=");
    Serial.println(CellVoltage19 * 0.001);
    client.print(CellVoltage19 * 0.001);
    client.print("&cellvoltage20=");  
    Serial.print("&cellvoltage20=");
    Serial.println(CellVoltage20 * 0.001);
    client.print(CellVoltage20 * 0.001);
    client.print("&temp1=");  
    Serial.print("&temp1=");
    Serial.println(t1);
    client.print(t1);
    client.print("&temp2=");  
    Serial.print("&temp2=");
    Serial.println(t2);
    client.print(t2);
    client.print("&temp3=");  
    Serial.print("&temp3=");
    Serial.println(t3);
    client.print(t3);
    client.print("&temp4=");  
    Serial.print("&temp4=");
    Serial.println(t4);
    client.print(t4);
    client.print("&temp5=");  
    Serial.print("&temp5=");
    Serial.println(t5);
    client.print(t5);
    client.print("&temp5=");  
    Serial.print("&temp5=");
    Serial.println(t5);
    client.print(t5);
    Serial.print("&serialnumber=");
    client.print("&serialnumber=");
    Serial.println(combinedString.substring(2, 8));
    client.print(combinedString.substring(2, 8));
    client.print(" HTTP/1.1");  
    client.println();
    client.println("Host: 192.168.1.11");
    client.println("Connection: close");
    client.println();
  } else {
    // if you didn't get a connection to the server:
    Serial.println("connection failed");
    digitalWrite(LED_BUILTIN, HIGH);   
  }
  // delay(1000);
}
